In [3]:
#|default_exp 03.02_app

## Revisiting Creating Simple Neural Networks

As I progress through Part 2 of the fastai course, I've discovered the value of occasionally retracing my steps to assess my grasp on the fundamental concepts. In my journey through Part 1, I recall Chapter 4 of the book being particularly daunting, as it covered a broad range of essential topics early on. However, this comprehensive approach was necessary to establish a strong foundation for everything I would subsequently learn.

Whenever I revisit those earlier chapters and analyze the code line by line, I'm often pleasantly surprised by the level of intuition I've developed in certain areas. Simultaneously, I'm also confronted with aspects that still elude my immediate understanding. Engaging in quick drills to reinforce these concepts has proven to be an effective method for staying sharp and achieving complete comprehension, even if it may feel somewhat repetitive. It's like eating vegetables as a child – you may not want to, but it's ultimately beneficial and necessary for growth. I believe that through a similar positive feedback loop, I will acquire a taste for this process and derive great rewards from it.

So, grab a fork and let's dig in

## Predicting Bank Loan Default from Synthetic Data

For this exercise I'm going to create synthetic data to predict whether a bank loan will default. I've chosen the following to create as features:

- Loan Amount 
- Term 
- Interest Rate 
- Borrower's Income 
- Borrower's Credit Score

## Generate Synthetic Data

In [4]:
#|export
import torch
torch.set_printoptions(precision=4, linewidth=140, threshold=500, sci_mode=False)

We're first going to create the data for 1000 samples randomly with `torch.normal`, to which we'll pass arguments for a *mean*, *standard deviation*, and *size*.

The size could be either a tuple or a list, but for this exercise we'll just use a tuple with a single value.

Also worth noting that `term` will be using `randint` rather than `normal`, because loan terms are generally in whole months.

In [5]:
#|export
n_samples = 1000
loan_amount = torch.normal(5000., 1500, size=(n_samples,))  # average loan amount is $5000
term = torch.randint(12, 60, size=(n_samples,))  # loan term varies between 1 and 5 years
interest_rate = torch.normal(0.05, 0.01, size=(n_samples,))  # average interest rate is 5%
income = torch.normal(50000, 10000, size=(n_samples,))  # average income is $50,000
credit_score = torch.normal(600, 50, size=(n_samples,))  # average credit score is 600

Next we'll stack the tensors and create a target variable where 10% of loans default, and convert them to *float32* data types in the process

In [6]:
#|export
x = torch.column_stack([loan_amount, term, interest_rate, income, credit_score]).float()
y = torch.distributions.categorical.Categorical(torch.tensor([0.9, 0.1])).sample((n_samples,)).float()

And normalize the data

In [28]:
x = torch.nn.functional.normalize(x).shape

torch.Size([1000, 5])

We'll also need to add a unit axis to our dependent variable so that it can be properly broadcast.

In [7]:
y.shape

torch.Size([1000])

This can be done using either `view` or specifying `None` on the axis we want to create

In [8]:
y.view(-1,1).shape

torch.Size([1000, 1])

In [9]:
y[:, None].shape

torch.Size([1000, 1])

In [10]:
#|export
y = y[:, None]

In [11]:
y.shape

torch.Size([1000, 1])

In [12]:
y

tensor([[0.],
        [0.],
        [1.],
        ...,
        [1.],
        [0.],
        [1.]])

Now that we have our data, let's move onto the creation of our neural network!

## Creating a Simple Neural Network with Pytorch

For this exercise, we're going to use 2 linear transformation layers, a *ReLU* activation layer with 3 nodes, and a sigmoid activation for the output to get our probability, between 0 and 1. To add a bit of an extra challege for myself I'm going to combine the steps into a class. Classes are something that I haven't had to use much yet, and this seems like a great opportunity to give myself some progressive overload on the mental muscles.

In [13]:
#|export
import torch.nn.functional as F

class SimpleNet(torch.nn.Module):
    def __init__(self):
        super(SimpleNet, self).__init__()
        self.lin_1 = torch.nn.Linear(5, 3)
        self.lin_2 = torch.nn.Linear(3, 1)

    def forward(self, x):
        x = self.lin_1(x)
        x = F.relu(x)
        x = self.lin_2(x)
        output = torch.sigmoid(x)
        return output

In [24]:
torch.sigmoid?

Docstring:
sigmoid(input, *, out=None) -> Tensor

Alias for :func:`torch.special.expit`.
Type:      builtin_function_or_method

In [14]:
#|export
model = SimpleNet()

In [17]:
model(x)

tensor([[0.],
        [0.],
        [0.],
        ...,
        [0.],
        [0.],
        [0.]], grad_fn=<SigmoidBackward0>)

Now we'll need to define a *Loss Function* to evaluate our model with, for simplicity, we'll use a *Mean Squared Error(MSE)*.

In [18]:
#|export
def mse(output, target):
    return (output - target).pow(2).mean()

We'll also need to specify our learning rate, and how we want to optimize our model, which is *Stochastic Gradient Descent(SGD)* in this case

In [19]:
#|export
lr = 1e-2

In [20]:
#|export
optimizer = torch.optim.SGD(model.parameters(), lr=lr)

In [21]:
print(model.parameters)

<bound method Module.parameters of SimpleNet(
  (lin_1): Linear(in_features=5, out_features=3, bias=True)
  (lin_2): Linear(in_features=3, out_features=1, bias=True)
)>


Now it's time to put it all in a loop, and run it a few times

In the loop we're going to:
- Generate predictions with our model
- Calculate the loss with our loss function
- Compute the gradients with respect to our parameters
- Update the parameters using our optimizer
- Zero the gradients to prepare for the next iteration

In [22]:
model(x)

tensor([[0.],
        [0.],
        [0.],
        ...,
        [0.],
        [0.],
        [0.]], grad_fn=<SigmoidBackward0>)

In [26]:
#|export
from tqdm import tqdm

epochs = 20
loss_fn = torch.nn.BCELoss()

for epoch in tqdm(range(epochs)):
    preds = model(x)
    loss = loss_fn(preds, y)
    print(f"Epoch: {epoch}, Loss: {loss}", flush=True)
    loss.backward()
    optimizer.step()
    optimizer.zero_grad()
    

  0%|          | 0/20 [00:00<?, ?it/s]

Epoch: 0, Loss: 11.100000381469727
Epoch: 1, Loss: 11.100000381469727
Epoch: 2, Loss: 11.100000381469727
Epoch: 3, Loss: 11.100000381469727
Epoch: 4, Loss: 11.100000381469727
Epoch: 5, Loss: 11.100000381469727
Epoch: 6, Loss: 11.100000381469727
Epoch: 7, Loss: 11.100000381469727
Epoch: 8, Loss: 11.100000381469727
Epoch: 9, Loss: 11.100000381469727
Epoch: 10, Loss: 11.100000381469727
Epoch: 11, Loss: 11.100000381469727
Epoch: 12, Loss: 11.100000381469727
Epoch: 13, Loss: 11.100000381469727
Epoch: 14, Loss: 11.100000381469727
Epoch: 15, Loss: 11.100000381469727
Epoch: 16, Loss: 11.100000381469727
Epoch: 17, Loss: 11.100000381469727
Epoch: 18, Loss: 11.100000381469727
Epoch: 19, Loss: 11.100000381469727


100%|██████████| 20/20 [00:00<00:00, 672.36it/s]


In [ ]:
import nbdev
nbdev.export.nb_export("03.02_gpt_teach_nn.ipynb", "03.02_app")