In [2]:
from torch import tensor
import torch

In [7]:
A = tensor([1,2,3])
B = tensor([4,5,6])

dot_product = torch.einsum('i,i->', A, B)
dot_product

tensor(32)

In [10]:
# elementwise multiplication
torch.einsum('i,i->i', A, B)

tensor([ 4, 10, 18])

In [41]:
A, B

(tensor([[1, 2],
         [3, 4]]),
 tensor([[5, 6],
         [7, 8]]))

In [13]:
A = tensor([[1, 2], [3, 4]])
B = tensor([[5, 6], [7, 8]])
A, B

(tensor([[1, 2],
         [3, 4]]),
 tensor([[5, 6],
         [7, 8]]))

In [16]:
# matrix multiplication
torch.einsum('ij, jk -> ik', A, B)

tensor([[19, 22],
        [43, 50]])

In [18]:
# matrix transposition
torch.einsum('ik -> ki', A)

tensor([[1, 3],
        [2, 4]])

In [21]:
X = tensor([1, 2, 3])
Y = tensor([4, 5, 6])


In [22]:
# elementwise multiplication
torch.einsum('i, i -> i', X, Y)

tensor([ 4, 10, 18])

In [24]:
M = tensor([[7, 8], [9, 10], [11, 12]])
M

tensor([[ 7,  8],
        [ 9, 10],
        [11, 12]])

In [26]:
# matrix transposition
torch.einsum('ij -> ji', M)

tensor([[ 7,  9, 11],
        [ 8, 10, 12]])

In [28]:
# A matrix
P = tensor([[1, 2], [3, 4], [5, 6]])

# A vector
Q = tensor([7, 8])
P, Q

(tensor([[1, 2],
         [3, 4],
         [5, 6]]),
 tensor([7, 8]))

In [49]:
P * Q

tensor([[ 7, 16],
        [21, 32],
        [35, 48]])

In [50]:
# broadcasting for elementwise addition
torch.einsum('ij, ...j -> ij', P, Q)

tensor([[ 7, 16],
        [21, 32],
        [35, 48]])

In [53]:
P @ Q

tensor([23, 53, 83])

In [52]:
# broadcasting for dot product
torch.einsum('ij, ...j -> i', P, Q)

tensor([23, 53, 83])

In [63]:
P + Q

tensor([[ 8, 10],
        [10, 12],
        [12, 14]])

In [66]:
torch.einsum('ij, ...j -> ij', P, Q)

tensor([[ 7, 16],
        [21, 32],
        [35, 48]])